### ISSUE TITLE
Patterns use

### ISSUE THREAD

**Issue by veselints** [BattleFieldTwo/Teamwork#23]
By now, we have implemented:
- Sigleton (in ConsoleView) - creational;
- Lazy initialization () - creational;
- Factory (MineFactory and CellFactory) - creational;
- Flyweight (within the factories) - structural;
- Template (to replace multiple inheritace of Mines) - structural;
- Command - implemented in WPF project - behaivioral;
- Decorator - implemented in WPF project - structural;
- Observer - implemented in WPF project - behaivioral;
- Memento (save/load game) - behaivioral;

**Comment by Vyara** [comment]
changed Decorator to Template Method, as new implementation of Mines no longer allows a Decorator pattern
