### ISSUE TITLE
Possible implementation of the Decorator pattern

### ISSUE THREAD

**Issue by Spurch** [BattleFieldTwo/Teamwork#3]
To use a simple/basic "mine" object class with properties/info common to all mines. We can use this class as a base on which we can "decorate" with specific mines. 
For example we can have a basic mine and "decorate" it up to a mine of type 1.
On the other hand if we want to have a type 2 mine then we get the basic mine, we "decorate" up to type 1 and then "add" type 2 decoration on top of the type.

**Comment by veselints** [comment]
I agree that it makes sence to try this approach.

**Comment by nklhtv** [comment]
This pattern is appropriate for this case.

**Comment by Vyara** [comment]
I agree on the decorator usage here.

**Comment by veselints** [comment]
Removed question tag as we all agree on this!

**Comment by Vyara** [comment]
What do you think of this implementation:
We create an interface IExplosive or an abstract class Explosive with one abstract method Detonate, which will be our Component. Then we have the Mine class(Concrete Component) and the Decorator(internal abstract class, accepting an Explosive object as a parameter in an protected constructor) inherit Explosive and override the Detonate method. We then create Concrete Decorators (TypeOneUpgrade, TypeTwoUpgrade, etc...), which will inherit Decorator and will override the Detonate method accordingly. This way, we leave an option for adding different types of explosives if needed.

**Comment by veselints** [comment]
I am OK with Viara's suggestion.
