### ISSUE TITLE
Possible implementation of the Prototype or Flyweight pattern

### ISSUE THREAD

**Issue by Spurch** [BattleFieldTwo/Teamwork#6]
We already have a basic "cell" object class that we use to create the "mines" and the "empty cells". We can try and use this for implementing a simple Prototype pattern in combination with the Factory that we already have.

**Comment by veselints** [comment]
We can better use flyweight in this case (https://en.wikipedia.org/wiki/Flyweight_pattern). It is a Structural DP, so we will have at least one of these :)
