### ISSUE TITLE
Data/information storage

### ISSUE THREAD

**Issue by Spurch** [BattleFieldTwo/Teamwork#8]
Since we were talking about Load/Save game feature that would require some basic Player register/login functionality. Both will require some data storage... we can implement a simple local DB for the project?

**Comment by veselints** [comment]
I think we an skip the register/login. We will ask the player for name of the game at save and save the states (saved games) in text file.

**Comment by Vyara** [comment]
I would go with Veselin on this one for the time being- not sure if we will have time for player login and possible DB, but if we do, we can redo it at a later point.

**Comment by Spurch** [comment]
We shall be writing and reading from a text file!
I shall close this issue shortly!

**Comment by Spurch** [comment]
Writing and reading to text implemented by @zvet80
